### ISSUE TITLE
Crash during game load

### ISSUE THREAD

**Issue by Kurtchekov** [McJtyMods/needtobreath#10]
Can't even get to the main menu, game keeps crashing even though I have provided Need to Breathe with the outdated version of Mcjtylib that it requires.

forge-14.23.5.2847
needtobreathe-1.12-0.4.0
mcjtylib-1.12-3.5.0
No Lost Cities

> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from NeedToBreathe (needtobreathe)
> Caused by: java.lang.NoClassDefFoundError: mcjty/needtobreathe/data/DimensionData
> 	at java.lang.Class.getDeclaredMethods0(Native Method)
> 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
> 	at java.lang.Class.getDeclaredMethod(Class.java:2128)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:93)
> 	at mcjty.needtobreathe.setup.ModSetup.preInit(ModSetup.java:30)
> 	at mcjty.needtobreathe.NeedToBreathe.preInit(NeedToBreathe.java:43)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
> 	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
> 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
> 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.ClassNotFoundException: mcjty.needtobreathe.data.DimensionData
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 46 more
> Caused by: java.lang.NullPointerException

**Comment by McJty** [comment]
Need To Breathe works fine with the latest McJtyLib. I'm not sure why you are using an old version? What error do you get if you do that?

**Comment by Kurtchekov** [comment]
I get the exact same error, regardless of what version of the library I use. I downgraded the library after the initial crash to see if that was the problem.

**Comment by LordPINE** [comment]
I can also confirm this issue, though not on my own pc. A friend of mine had the crash (and I didn't, with the same pack), so it seems to be something outside of the pack that's interfering. For reference, here is the crash report: https://gist.github.com/LordPINE/16ee53a9ec09f7a1898043693001abcf

**Comment by Kurtchekov** [comment]
I think I might have figured out what's happening: Bitdefender Antivirus is silently blocking DimensionData.class file under the presumption of it being a threat (Java.Trojan.GenericGBA.5554). Is this friend of yours also user Bitdefender? If so, they should add that file to the exclusion list. Hope it helps.

**Comment by LordPINE** [comment]
Yeah, he also has bitdefender, which indeed seems to be causing the issue. Thanks for the help!
