### ISSUE TITLE
[1.12.2-0.4.0] Windows Security detects the presence of the "Multiverze" malware

### ISSUE THREAD

**Issue by RnChan408** [McJtyMods/needtobreath#12]
I'm not really willing to test with other versions but currently, Windows Security detectthe "Mulitverze" trojan within the jar. This never popped up until recently for me but it'seems to either be: 

1. The result of a bait and switch with the download. Worrying since there was a comment on the curseforge page about this happening an entire year before the time of writing this issue.
2. This malware was present the entire time since the original upload. Even more worrying since I that would mean that this malware has been present the entire time intentionally or not. 
3. This mop was a victim of one of the last couple attacks on curseforge in 2023, and the file was replaced

The last one is the most optimistic of the three, but that's not necessarily a good thing. As of right now you can still download it.

Link to the virus Windows Security detects on downloading this mod: 
[https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AAndroidOS%2FMultiverze&threatid=2147785333](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AAndroidOS%2FMultiverze&threatid=2147785333)

EDIT: For people who have the mod downloaded, it's probably for the best you don't unzip the mod. There's no guarantee that unzipping won't trigger the virus.

**Comment by McJty** [comment]
This is a false alarm. The mod doesn't contain any virus. I just downloaded it myself and it's just a pure java jar file with mod. Not sure why Windows security is being triggered but this alarm is false
