### ISSUE TITLE
[Feature Request] Integration EP (Electrotine Power, ProjectRed energy) with MJ, EU, RF

### ISSUE THREAD

**Issue by Babo357** [McJtyMods/needtobreath#6]
Hi, thanks for all your mods, ProjectRed is amazing.
Is it possible to integrate with other mods (like IC2, Buildcraft, Forestry, etc.) the ProjectRed energy sytem?, Make compatible even the "low load power line" with alloy wire/insulated wires, or the creation of a machine thats convert electrotine power (EP) to MJ, Tesla, RF, FE, etc.

Thanks!!!

**Comment by McJty** [comment]
Wrong mod? I don't have anything to do with ProjectRed
