### ISSUE TITLE
Air Compressor Won't Accept RF Energy

### ISSUE THREAD

**Issue by BTRBT** [McJtyMods/needtobreath#7]
The air compressor won't accept RF energy from capacitors, wires, or conduits in Immersive Engineering or Ender IO. Both powered purifiers do, however. 

I only have NeedToBreathe, McJtyLib, and either Immersive Engineering or EnderIO (with EnderCore) installed when testing. The air compressor is unobstructed, and I've tried inputting to each block face. Config is default, aside from enabling poison in the overworld for testing. Using mcjtylib-1.12-3.1.1 and needtobreathe-1.12-0.3.1 which are the latest releases on Curse. Using Forge 14.23.5.2824, which is the latest version available for 1.12.2.

Thanks for the awesome mod! If there's anything else I can do, please let me know. I unfortunately don't know Java well enough to bug-hunt myself, despite the MIT license.

**Comment by McJty** [comment]
It works fine with RF energy. The only problem is that it doesn't visually show in the GUI that it has power. But The One Probe shows it is getting power fine. I'll fix the display issue though
