### ISSUE TITLE
Hazmat Suit Air Supply Goes Negative

### ISSUE THREAD

**Issue by BTRBT** [McJtyMods/needtobreath#8]
The hazmat suit air value drops below zero. I don't know if this intentional design, but it certainly _feels_ like a bug. Value can drop below 100. I only have NeedToBreath and McJtyLib installed when testing this. Config is default, aside from enabling poison in the overworld for testing. Using mcjtylib-1.12-3.1.1 and needtobreathe-1.12-0.3.1 which are the latest releases on Curse. Using Forge 14.23.5.2824, which is the latest version available for 1.12.2. Screencap of tooltip: https://i.imgur.com/Ffpb7gu.png

Once again, thanks for the awesome mod! Cheers.

**Comment by McJty** [comment]
Hmm, any clue when this started happening?

**Comment by McJty** [comment]
Never mind. I can reproduce it

**Comment by McJty** [comment]
Fixed next release
