### ISSUE TITLE
creativePurifierAutogenerate doesn't seem to do anything?

### ISSUE THREAD

**Issue by pharaun** [McJtyMods/needtobreath#9]
I poked around in the source and it doesn't seem to be used in anything?

I was also unable to determite if the creative cleaner + lost city biosphere worked in the space profile. I could place down a creative filter but it would only clean to 50 block radius, but no more. and I visually dug around at the center and at 0 in the sphere to see if I could find one and I couldn't.

I did see you have an event in the code for generating it with the lost city spheres but as far as I could tell, I couldn't get them to generate.

**Comment by McJty** [comment]
The creative purifier is a worldgen block that is only useful in combination with lost cities. It is not something you should use own your own. What do you want to do?

**Comment by pharaun** [comment]
I was under the impression that if i set the creativePurifierAutogenerate to 1.0, plus from the code here https://github.com/McJtyMods/needtobreath/blob/cf7af50dc6e1869f56ea5f89e7b18a5ee8545698/src/main/java/mcjty/needtobreathe/compat/LostCitySupport.java#L47-L64

Seems to indicate that the creative purifier should already be generated whenever I create a new world with Lost City spheres profiles (ie space). But as far as I can tell, it doesn't?

To answer your question more directly, what I was hoping to do was to have all of the lost city spheres generate with this creative cleaner already included/built in to the sphere and it cleaning the sphere. I want to make the outside air outside of the spheres to be poisonous to make the player don protective gear when they venue outside of the spheres.

**Comment by pharaun** [comment]
This seems to work in the profile_biosphere but not profile_waterbubble or profile_space so I'm continuing to dig to see what is going on.

**Comment by pharaun** [comment]
Ok I'm unable to reproduce it with *only* Lost City and Need to Breath. So I'm starting to suspect some sort of cross-mod interaction. I'll update when I find out what it is and close.

**Comment by pharaun** [comment]
Ok I've tracked it down to CustomOreGeneration, it was conflicting, I've worked around it, closing.
